import { Project, ProjectData } from '@/types';

export const PROJECTS: ProjectData = {
  CostAccounting: {
    name: 'Costy',
    description:
      'Mobile application that tracks expenses and incomes while suggesting affordability guidance for upcoming purchases.',
    categories: ['Fintech', 'FamilyOps'],
    status: 'R&D',
    summary:
      'Scores household transactions, forecasts cash flow, and nudges affordability-aligned decisions with AI-powered recommendations.',
    highlight:
      'Reads current financial strategy and forecasts affordability for next purchases every month.',
    tags: ['Fintech', 'Automation', 'FamilyOps'],
    stack: ['Java 21', 'Micronaut', 'Microservices', 'PostgreSQL', 'React JS'],
    roles: ['Creator', 'Developer'],
    featured: true,
    weight: 90,
    publishedAt: '2024-04-01',
    slug: '/projects/cost-accounting',
    link: 'https://costy.posadskiy.com',
    body: `What started as a weekend helper for my family evolved into Costy: a mobile companion that captures every expense and income while modeling the household financial strategy. Microservices built with Micronaut and PostgreSQL keep the ledger consistent, and React JS surfaces affordability nudges derived from AI forecasts so we know whether the next purchase fits this month’s plan. Each release strengthens microservice orchestration and recommendation tuning to mirror real-life rituals.`,
  },
  CurrencyConverter: {
    name: 'Currency Converter',
    description:
      'Open-source Java library that integrates three common FX providers and exposes a single interface for the consuming application.',
    categories: ['Fintech', 'Open Source'],
    status: 'Open Source',
    summary:
      'Wraps three popular exchange-rate APIs under one dependency so teams can begin pulling deterministic rates with a single call.',
    highlight:
      'Single API, multi-provider coverage so apps get rates as soon as they depend on the library.',
    tags: ['Libraries', 'Finance', 'APIs'],
    stack: ['Java 8'],
    roles: ['Creator', 'Developer', 'Maintainer'],
    featured: true,
    weight: 80,
    publishedAt: '2023-11-12',
    slug: '/projects/currency-converter',
    link: 'https://github.com/posadskiy/currency-converter',
    body: `Currency Converter wires together three of the most commonly used FX feeds and exposes one clean interface so a JVM service only needs to drop in the dependency to start retrieving rates. Everything else—aggregation, cache, and provider failover—is hidden behind that API surface, making it possible to start using live exchange information without wiring multiple providers or managing refresh schedules. The open-source source, https://github.com/posadskiy/currency-converter, is all you need to get started.`,
  },
  SkillRepeater: {
    name: 'Repeaty',
    description: 'Web application that reminds you to refresh skills on your chosen cadence.',
    categories: ['Learning'],
    status: 'Beta',
    summary:
      'Schedules reminders for the skills you select and keeps the cadence in sync with your preferred intervals.',
    highlight: 'Keeps muscle memory sharp by nudging you when practice windows open.',
    tags: ['Learning', 'Productivity', 'Notifications'],
    stack: ['Java 21', 'Micronaut', 'Microservices', 'React JS', 'PostgreSQL'],
    roles: ['Creator', 'Developer'],
    featured: false,
    weight: 70,
    publishedAt: '2022-09-05',
    slug: '/projects/skill-repeater',
    link: 'https://repeaty.posadskiy.com',
    body: `Repeaty catalogs skills you care about, collects your desired refresh rhythm, and fires personalized reminders exactly when the next practice window opens. Microservices in Micronaut handle scheduling, state modeling, and notifications while React JS surfaces streaks and policy controls. PostgreSQL keeps histories auditable so users can prove their continuous learning.`,
  },
  StudyEveryday: {
    name: 'Study Everyday',
    description:
      'Knowledge companion that keeps learning rituals in sync with curated algos, architecture, and language notes.',
    categories: ['Learning', 'Open Source'],
    status: 'Released',
    summary:
      'Catalogs algorithms, architecture notes, build tips, and language experiments so curiosity stays measurable and spread across domains.',
    highlight: 'Navigable knowledge stacks for planned learning and recall.',
    tags: ['Learning', 'Knowledge', 'Open Source'],
    stack: ['Java 23', 'Maven', 'Spring', 'Lombok', 'Log4j', 'React', 'React Native'],
    roles: ['Creator'],
    featured: false,
    weight: 65,
    publishedAt: '2021-02-17',
    slug: '/projects/study-everyday',
    link: 'https://github.com/posadskiy/study-everyday',
    body: `Study Everyday captures learning across algorithms, architecture, build, design, databases, deployment, framework, language, and protocol topics so every note maps back to practical references.`,
  },
  BankWork: {
    name: 'Bank work',
    description: 'Unified mobile and desktop cockpit for relationship managers.',
    categories: ['Fintech', 'Enterprise'],
    status: 'Released',
    summary:
      'Consolidates CRM, tasking, onboarding, and compliance flows into a single secure workspace.',
    highlight: 'Reduced context switching for 400+ client managers.',
    tags: ['Enterprise', 'Banking', 'Productivity'],
    stack: ['Java', 'Spring', 'React', 'React Native', 'RabbitMQ'],
    roles: ['Senior Full Stack Developer'],
    featured: true,
    weight: 75,
    publishedAt: '2020-08-01',
    slug: '/projects/bank-work',
    body: `Bank Work consolidates CRM, tasking, onboarding, and compliance flows into a single secure workspace. We developed frontend and backend so managers can respond to clients from any device without losing auditability. Feature toggles let us roll out new flows to pilot branches while keeping the rest of the bank stable.`,
  },
  IoTWork: {
    name: 'IoT work',
    description:
      'Intelligent climate control system for commercial buildings with synchronized server, client, and embedded teams.',
    categories: ['IoT', 'Enterprise'],
    status: 'Released',
    summary:
      'Managed server and client development, modernizing architecture, lifting code quality, and coordinating releases so device teams moved faster.',
    highlight:
      'Coached a full-stack/AI/AQA pod, deployed CI/testing/security, and aligned embedded/servers for predictable releases.',
    tags: ['IoT', 'Enterprise', 'Team Leadership'],
    stack: ['Java', 'Play Framework', 'JavaScript', 'GitLab', 'Git', 'Asana', 'Slite'],
    roles: ['Head of Server Software'],
    featured: false,
    weight: 60,
    publishedAt: '2019-06-10',
    slug: '/projects/iot-work',
    link: 'https://setpoint.ai',
    body: `I participated in and manage development of both server and client parts, introduced CI, performance testing, security checks, and a unified database, and orchestrated a shared release cadence. Stand-ups, knowledge exchanges, candidate interviews, and onboarding keep the full-stack, AI, and AQA specialists aligned. As a result releases ship on time (without overtime), development speed quintupled, communication between server and embedded teams improved, and operator reporting became automated, routing device issues to curated solutions.`,
  },
  SwingTutor: {
    name: 'Java Swing Tutor',
    description: 'IDE-with-lessons that guides newcomers to production-grade Java Swing.',
    categories: ['Learning'],
    status: 'Open Source',
    summary:
      'Packages exercises, tests, and UI previews so students learn Swing with immediate feedback.',
    highlight: 'Pairs IDE actions with contextual lessons.',
    tags: ['Education', 'Desktop', 'Java'],
    stack: ['Java Swing', 'Maven', 'JUnit'],
    roles: ['Creator', 'Developer'],
    featured: false,
    weight: 55,
    publishedAt: '2018-03-04',
    slug: '/projects/swing-tutor',
    link: 'https://java-swing.com',
    body: `Java Swing Tutor packages curated exercises, test harnesses, and UI previews into one teaching IDE. Students read a short brief, run the scaffold, then the app validates their implementation against unit tests.`,
  },
  ScheduleEditor: {
    name: 'Schedule Editor',
    description:
      'Desktop planner that keeps university lesson calendars consistent across faculties.',
    categories: ['Enterprise', 'Learning'],
    status: 'Released',
    summary:
      'Replaced fragile spreadsheets with conflict-aware scheduling for classrooms, professors, and groups.',
    highlight: 'Drag-and-drop timetables with instant conflict detection.',
    tags: ['Desktop', 'Education', 'Planning'],
    stack: ['JavaFX', 'SQLite', 'Apache POI'],
    roles: ['Lead Developer'],
    featured: false,
    weight: 50,
    publishedAt: '2017-01-15',
    slug: '/projects/schedule-editor',
    link: 'https://github.com/posadskiy/schedule-editor',
    body: `Schedule Editor was built to replace fragile spreadsheets used by faculty admins. It keeps classrooms, professors, and student groups in sync and exports read-only schedules to PDF/Excel for distribution. Conflict detection happens as you drag lessons around, which cut rescheduling time during exam seasons drastically.`,
  },
  UserComponentReact: {
    name: 'User Component React',
    description:
      'Open-source React component library for managing user profiles, built with Material-UI and TypeScript.',
    categories: ['Open Source'],
    status: 'Open Source',
    summary:
      'Drop-in React component that fetches, displays, and updates a user profile via a configurable API URL with JWT support.',
    highlight: 'Single component, full CRUD profile management with MUI styling out of the box.',
    tags: ['React', 'Open Source', 'Libraries'],
    stack: ['React', 'TypeScript', 'Material-UI'],
    roles: ['Creator', 'Developer'],
    featured: false,
    weight: 46,
    publishedAt: '2025-01-01',
    slug: '/projects/user-component-react',
    link: 'https://github.com/posadskiy/user-component-react',
    body: `User Component React is a zero-configuration drop-in for any React app that needs profile management. Pass an API URL and an optional JWT, and the component handles fetching, editing, and deleting the user record while surfacing error and success callbacks. Material-UI powers the responsive card layout so teams can ship polished profile screens without hand-rolling UI.`,
  },
  AuthComponentReact: {
    name: 'Auth Component React',
    description:
      'Open-source React component library providing ready-made Login and Register forms with OAuth provider support.',
    categories: ['Open Source', 'Security'],
    status: 'Open Source',
    summary:
      'Plug-in Login and Register components backed by Mantine UI and React Query, supporting custom API hooks and six OAuth providers.',
    highlight: 'Full auth UI—username/password and OAuth—in a single npm install.',
    tags: ['React', 'Open Source', 'Libraries', 'Auth'],
    stack: ['React', 'TypeScript', 'Mantine UI', 'React Query'],
    roles: ['Creator', 'Developer'],
    featured: false,
    weight: 48,
    publishedAt: '2025-01-01',
    slug: '/projects/auth-component-react',
    link: 'https://github.com/posadskiy/auth-component-react',
    body: `Auth Component React ships production-ready Login and Register forms so any React app can add authentication without writing UI from scratch. Mantine UI and React Query handle rendering and request state while the flexible API layer accepts either a base URL or fully custom fetch functions. Six OAuth buttons—Google, Apple, Microsoft, GitHub, Discord, Facebook—render on demand via feature flags, making it straightforward to extend the login screen as providers are added.`,
  },
  RestSecurity: {
    name: 'Rest Security',
    description: 'Open-source library that hardens Java APIs with proven security patterns.',
    categories: ['Security', 'Enterprise'],
    status: 'Community',
    summary:
      'Ships pre-configured guards so teams get rate limiting, audit trails, and consent enforcement.',
    highlight: 'Batteries-included security without the ceremony.',
    tags: ['Security', 'OSS', 'Java'],
    stack: ['Java', 'Spring Security'],
    roles: ['Maintainer'],
    featured: true,
    weight: 85,
    publishedAt: '2016-05-20',
    slug: '/projects/rest-security',
    link: 'https://github.com/posadskiy/rest-security',
    body: `REST Security ships pre-configured guards—rate limiting, audit trails, and consent enforcement—so product teams can focus on their domain logic. I maintain the release train, triage issues from the community, and keep the guidance aligned with the latest OWASP and OWASP API Security recommendations.`,
  },
};

export const getAllProjects = (): Project[] => Object.values(PROJECTS);
