import { Project, ProjectData } from '@/types';

export const PROJECTS: ProjectData = {
  CostAccounting: {
    name: 'Costy',
    description:
      'Collaborative budget platform for tracking purchases and incomes across shared projects, with spending analytics and category-level limits.',
    body: "You create a shared project and invite family members or teammates by invite code, so everyone logs purchases and incomes into the same ledger. Each transaction is tagged with a category and currency, and you can set a spending limit per category per project so the dashboard immediately shows how close you are to the cap. The statistics view breaks down the month by day, letting you spot when spending spikes, compare purchase and income totals by category, or drill into a single member's activity. A profile layer keeps each user's active project in sync, so switching context between personal and shared budgets is one tap.",
    categories: ['Fintech', 'FamilyOps'],
    status: 'Beta',
    tags: ['Fintech', 'Finance'],
    stack: ['Java 25', 'Micronaut', 'Microservices', 'PostgreSQL', 'React JS'],
    roles: ['Creator', 'Developer'],
    weight: 90,
    from: '2019-09-14',
    to: 'now',
    slug: '/projects/cost-accounting',
    link: 'https://costy.posadskiy.com',
  },
  SkillRepeater: {
    name: 'Repeaty',
    description:
      'Spaced-repetition platform for tracking skills with configurable intervals, priority levels, and email reminders when repetitions are due.',
    body: "You add a skill, pick how often you want to revisit it — anything from every few hours to once a year — and assign a priority from Low to Critical so the most important things surface first. Every time you mark a skill as practiced, its level goes up and the next due date shifts forward automatically. When a repetition window opens, Repeaty sends you an email reminder so nothing falls through the cracks even if you haven't logged in. Over time the history log shows exactly when you last practiced each skill and how your levels have grown, giving you a concrete picture of consistency across everything you're trying to keep sharp.",
    categories: ['Learning'],
    status: 'Beta',
    tags: ['Learning', 'Productivity'],
    stack: ['Java 25', 'Micronaut', 'Microservices', 'React JS', 'PostgreSQL'],
    roles: ['Creator', 'Developer'],
    weight: 80,
    from: '2019-01-05',
    to: 'now',
    slug: '/projects/skill-repeater',
    link: 'https://repeaty.posadskiy.com',
  },
  CurrencyConverter: {
    name: 'Currency Converter',
    description:
      'Open-source Java library that integrates three common FX providers and exposes a single interface for the consuming application.',
    categories: ['Fintech', 'Open Source'],
    status: 'Stable',
    body: 'Single API, multi-provider coverage so apps get rates as soon as they depend on the library.',
    tags: ['Libraries', 'Finance', 'APIs'],
    stack: ['Java 8'],
    roles: ['Creator', 'Developer', 'Maintainer'],
    weight: 60,
    from: '2023-11-12',
    to: 'now',
    slug: '/projects/currency-converter',
    link: 'https://github.com/posadskiy/currency-converter',
  },
  StudyEveryday: {
    name: 'Study Everyday',
    description:
      'Knowledge companion that keeps learning rituals in sync with curated algos, architecture, and language notes.',
    categories: ['Learning', 'Open Source'],
    status: 'Stable',
    body: 'Navigable knowledge stacks for planned learning and recall.',
    tags: ['Learning', 'Knowledge', 'Open Source'],
    stack: ['Java 23', 'Maven', 'Spring', 'Lombok', 'Log4j', 'React', 'React Native'],
    roles: ['Creator'],
    weight: 40,
    from: '2021-02-17',
    to: 'now',
    slug: '/projects/study-everyday',
    link: 'https://github.com/posadskiy/study-everyday',
  },
  SwingTutor: {
    name: 'Java Swing Tutor',
    description: 'IDE-with-lessons that guides newcomers to production-grade Java Swing.',
    categories: ['Learning'],
    status: 'Beta',
    body: 'Pairs IDE actions with contextual lessons.',
    tags: ['Education', 'Desktop', 'Java'],
    stack: ['Java Swing', 'Maven', 'JUnit'],
    roles: ['Creator', 'Developer'],
    weight: 70,
    from: '2018-03-04',
    to: 'now',
    slug: '/projects/swing-tutor',
    link: 'https://java-swing.com',
  },
  BankWork: {
    name: 'Bank work',
    description: 'Unified mobile and desktop cockpit for relationship managers.',
    categories: ['Fintech', 'Enterprise'],
    status: 'Delivered',
    body: 'Reduced context switching for 400+ client managers.',
    tags: ['Enterprise', 'Banking', 'Productivity'],
    stack: ['Java', 'Spring', 'React', 'React Native', 'RabbitMQ'],
    roles: ['Senior Full Stack Developer'],
    weight: 50,
    from: '2016-08-01',
    slug: '/projects/bank-work',
  },
  IoTWork: {
    name: 'IoT work',
    description:
      'Intelligent climate control system for commercial buildings with synchronized server, client, and embedded teams.',
    categories: ['IoT', 'Enterprise'],
    status: 'Delivered',
    body: 'Coached a full-stack/AI/AQA pod, deployed CI/testing/security, and aligned embedded/servers for predictable releases.',
    tags: ['IoT', 'Enterprise', 'Team Leadership'],
    stack: ['Java', 'Play Framework', 'JavaScript', 'GitLab', 'Git', 'Asana', 'Slite'],
    roles: ['Head of Server Software'],
    weight: 55,
    from: '2019-06-10',
    slug: '/projects/iot-work',
    link: 'https://setpoint.ai',
  },
  ScheduleEditor: {
    name: 'Schedule Editor',
    description:
      'Desktop planner that keeps university lesson calendars consistent across faculties.',
    categories: ['Enterprise', 'Learning'],
    status: 'Stable',
    body: 'Drag-and-drop timetables with instant conflict detection.',
    tags: ['Desktop', 'Education', 'Planning'],
    stack: ['JavaFX', 'SQLite', 'Apache POI'],
    roles: ['Lead Developer'],
    weight: 20,
    from: '2017-01-15',
    to: 'now',
    slug: '/projects/schedule-editor',
    link: 'https://github.com/posadskiy/schedule-editor',
  },
  UserComponentReact: {
    name: 'User Component React',
    description:
      'Open-source React component library for managing user profiles, built with Material-UI and TypeScript.',
    categories: ['Open Source'],
    status: 'Stable',
    body: 'Single component, full CRUD profile management with MUI styling out of the box.',
    tags: ['React', 'Open Source', 'Libraries'],
    stack: ['React', 'TypeScript', 'Material-UI'],
    roles: ['Creator', 'Developer', 'Maintainer'],
    weight: 45,
    from: '2025-01-01',
    to: 'now',
    slug: '/projects/user-component-react',
    link: 'https://github.com/posadskiy/user-component-react',
  },
  AuthComponentReact: {
    name: 'Auth Component React',
    description:
      'Open-source React component library providing ready-made Login and Register forms with OAuth provider support.',
    categories: ['Open Source', 'Security'],
    status: 'Stable',
    body: 'Full auth UI—username/password and OAuth—in a single npm install.',
    tags: ['React', 'Open Source', 'Libraries', 'Auth'],
    stack: ['React', 'TypeScript', 'Mantine UI', 'React Query'],
    roles: ['Creator', 'Developer', 'Maintainer'],
    weight: 48,
    from: '2025-01-01',
    to: 'now',
    slug: '/projects/auth-component-react',
    link: 'https://github.com/posadskiy/auth-component-react',
  },
  RestSecurity: {
    name: 'Rest Security',
    description: 'Open-source library that hardens Java APIs with proven security patterns.',
    categories: ['Security', 'Enterprise'],
    status: 'Stable',
    body: 'Batteries-included security without the ceremony.',
    tags: ['Security', 'OSS', 'Java'],
    stack: ['Java', 'Spring Security'],
    roles: ['Maintainer'],
    weight: 10,
    from: '2016-05-20',
    to: 'now',
    slug: '/projects/rest-security',
    link: 'https://github.com/posadskiy/rest-security',
  },
};

export const getAllProjects = (): Project[] => Object.values(PROJECTS);
