import { Project, ProjectData } from '@/types';

export const PROJECTS: ProjectData = {
  CostAccounting: {
    name: 'Costy',
    description:
      'Mobile and Web application that tracks expenses and incomes, provide statistics and analytics',
    categories: ['Fintech', 'FamilyOps'],
    status: 'Beta',
    body: 'Evaluate current financial strategy, provides insides on current month statistics and limits',
    tags: ['Fintech', 'Automation', 'FamilyOps'],
    stack: ['Java 25', 'Micronaut', 'Microservices', 'PostgreSQL', 'React JS'],
    roles: ['Creator', 'Developer'],
    weight: 90,
    from: '2019-09-14',
    to: 'now',
    slug: '/projects/cost-accounting',
    link: 'https://costy.posadskiy.com',
  },
  SkillRepeater: {
    name: 'Repeaty',
    description: 'Web application that reminds you to refresh skills on your chosen cadence.',
    categories: ['Learning'],
    status: 'Beta',
    body: 'Keeps muscle memory sharp by nudging you when practice windows open.',
    tags: ['Learning', 'Productivity', 'Notifications'],
    stack: ['Java 21', 'Micronaut', 'Microservices', 'React JS', 'PostgreSQL'],
    roles: ['Creator', 'Developer'],
    weight: 80,
    from: '2019-01-05',
    to: 'now',
    slug: '/projects/skill-repeater',
    link: 'https://repeaty.posadskiy.com',
  },
  CurrencyConverter: {
    name: 'Currency Converter',
    description:
      'Open-source Java library that integrates three common FX providers and exposes a single interface for the consuming application.',
    categories: ['Fintech', 'Open Source'],
    status: 'Stable',
    body: 'Single API, multi-provider coverage so apps get rates as soon as they depend on the library.',
    tags: ['Libraries', 'Finance', 'APIs'],
    stack: ['Java 8'],
    roles: ['Creator', 'Developer', 'Maintainer'],
    weight: 60,
    from: '2023-11-12',
    to: 'now',
    slug: '/projects/currency-converter',
    link: 'https://github.com/posadskiy/currency-converter',
  },
  StudyEveryday: {
    name: 'Study Everyday',
    description:
      'Knowledge companion that keeps learning rituals in sync with curated algos, architecture, and language notes.',
    categories: ['Learning', 'Open Source'],
    status: 'Stable',
    body: 'Navigable knowledge stacks for planned learning and recall.',
    tags: ['Learning', 'Knowledge', 'Open Source'],
    stack: ['Java 23', 'Maven', 'Spring', 'Lombok', 'Log4j', 'React', 'React Native'],
    roles: ['Creator'],
    weight: 40,
    from: '2021-02-17',
    to: 'now',
    slug: '/projects/study-everyday',
    link: 'https://github.com/posadskiy/study-everyday',
  },
  SwingTutor: {
    name: 'Java Swing Tutor',
    description: 'IDE-with-lessons that guides newcomers to production-grade Java Swing.',
    categories: ['Learning'],
    status: 'Beta',
    body: 'Pairs IDE actions with contextual lessons.',
    tags: ['Education', 'Desktop', 'Java'],
    stack: ['Java Swing', 'Maven', 'JUnit'],
    roles: ['Creator', 'Developer'],
    weight: 70,
    from: '2018-03-04',
    to: 'now',
    slug: '/projects/swing-tutor',
    link: 'https://java-swing.com',
  },
  BankWork: {
    name: 'Bank work',
    description: 'Unified mobile and desktop cockpit for relationship managers.',
    categories: ['Fintech', 'Enterprise'],
    status: 'Delivered',
    body: 'Reduced context switching for 400+ client managers.',
    tags: ['Enterprise', 'Banking', 'Productivity'],
    stack: ['Java', 'Spring', 'React', 'React Native', 'RabbitMQ'],
    roles: ['Senior Full Stack Developer'],
    weight: 50,
    from: '2016-08-01',
    slug: '/projects/bank-work',
  },
  IoTWork: {
    name: 'IoT work',
    description:
      'Intelligent climate control system for commercial buildings with synchronized server, client, and embedded teams.',
    categories: ['IoT', 'Enterprise'],
    status: 'Delivered',
    body: 'Coached a full-stack/AI/AQA pod, deployed CI/testing/security, and aligned embedded/servers for predictable releases.',
    tags: ['IoT', 'Enterprise', 'Team Leadership'],
    stack: ['Java', 'Play Framework', 'JavaScript', 'GitLab', 'Git', 'Asana', 'Slite'],
    roles: ['Head of Server Software'],
    weight: 55,
    from: '2019-06-10',
    slug: '/projects/iot-work',
    link: 'https://setpoint.ai',
  },
  ScheduleEditor: {
    name: 'Schedule Editor',
    description:
      'Desktop planner that keeps university lesson calendars consistent across faculties.',
    categories: ['Enterprise', 'Learning'],
    status: 'Stable',
    body: 'Drag-and-drop timetables with instant conflict detection.',
    tags: ['Desktop', 'Education', 'Planning'],
    stack: ['JavaFX', 'SQLite', 'Apache POI'],
    roles: ['Lead Developer'],
    weight: 20,
    from: '2017-01-15',
    to: 'now',
    slug: '/projects/schedule-editor',
    link: 'https://github.com/posadskiy/schedule-editor',
  },
  UserComponentReact: {
    name: 'User Component React',
    description:
      'Open-source React component library for managing user profiles, built with Material-UI and TypeScript.',
    categories: ['Open Source'],
    status: 'Stable',
    body: 'Single component, full CRUD profile management with MUI styling out of the box.',
    tags: ['React', 'Open Source', 'Libraries'],
    stack: ['React', 'TypeScript', 'Material-UI'],
    roles: ['Creator', 'Developer', 'Maintainer'],
    weight: 45,
    from: '2025-01-01',
    to: 'now',
    slug: '/projects/user-component-react',
    link: 'https://github.com/posadskiy/user-component-react',
  },
  AuthComponentReact: {
    name: 'Auth Component React',
    description:
      'Open-source React component library providing ready-made Login and Register forms with OAuth provider support.',
    categories: ['Open Source', 'Security'],
    status: 'Stable',
    body: 'Full auth UI—username/password and OAuth—in a single npm install.',
    tags: ['React', 'Open Source', 'Libraries', 'Auth'],
    stack: ['React', 'TypeScript', 'Mantine UI', 'React Query'],
    roles: ['Creator', 'Developer', 'Maintainer'],
    weight: 48,
    from: '2025-01-01',
    to: 'now',
    slug: '/projects/auth-component-react',
    link: 'https://github.com/posadskiy/auth-component-react',
  },
  RestSecurity: {
    name: 'Rest Security',
    description: 'Open-source library that hardens Java APIs with proven security patterns.',
    categories: ['Security', 'Enterprise'],
    status: 'Stable',
    body: 'Batteries-included security without the ceremony.',
    tags: ['Security', 'OSS', 'Java'],
    stack: ['Java', 'Spring Security'],
    roles: ['Maintainer'],
    weight: 10,
    from: '2016-05-20',
    to: 'now',
    slug: '/projects/rest-security',
    link: 'https://github.com/posadskiy/rest-security',
  },
};

export const getAllProjects = (): Project[] => Object.values(PROJECTS);
